### PR TITLE
List structure

### PR DESCRIPTION
**Pull request by akos29**
### To-Do List: Add and Remove

This request majorly included:

- Add JavaScript functionality to add task
- Add functionality to remove and edit 
- Add functionality for removing and sorting the list indexes 
- Add functionality saving To-Do tasks in local storage

### CODE REVIEW

**Review by GiuseppeTG — CHANGES_REQUESTED** [review]
Hi @akos29  👋 , 

Good job so far!
There are some issues that you still need to work on to go to the next project but you are almost there!

Alt Text

## Highlights
✅ Professional pull request
✅ Good UI
✅ Add function works

## Required Changes ♻️
_Check the comments under the review._

## Optional suggestions
_Every comment with the [OPTIONAL] prefix is not crucial enough to stop the approval of this PR. However, I strongly recommend you to take them into account as they can make your code better._

Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
Please, remember to tag me in your question so I can receive the notification.

**_Please, do not open a new Pull Request for re-reviews. You should use the same Pull Request submitted for the first review, either valid or invalid unless it is requested otherwise._**

------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561) you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._

**Comment by GiuseppeTG** [comment]
- [x] When deleting a task the order value of the other task does not change in the local storage. Kindly fix this problem as the order value does not reflect the correct value after a delete. 🤓

**Comment by GiuseppeTG** [comment]
- [x] When a task is marked as done, the value of completed in the local storage should update to true. Kindly implement this properly 👍

**Comment by GiuseppeTG** [comment]
- [x] When I try to update a task the app stops working, I am not sure if this is a problem on my end or it is a bug in your app.

Also, it would be good to clear the console logs there are in your code, just to make it look cleaner. 🤓 

I will leave here a video where you can see the errors that I mentioned before. 👀 
The next reviewer can test if he has the same issues 👍 

https://user-images.githubusercontent.com/86022690/199787438-27788dad-353a-41e3-9934-fa84ce54d0a0.mov

**Review by Alfredbis29 — APPROVED** [review]
# STATUS: APPROVED  
 ## Hi @akos29 ,
Your project is complete! There is nothing else to say other than... Great job clap Congratulations! :tada:
 
 TO HIGHLIGHT:
 
 * Your project is professional :white_check_mark:
 * Your repo is professional :white_check_mark:
 * Well structured files :white_check_mark:
 * No Linter errors :white_check_mark:
 
 Now you can merge this branch and move on :1st_place_medal: HAPPY CODING AND GOOD LUCK WITH THE COMMING ONES :crossed_fingers four_leaf_clover:


 
 ## Optional suggestions
 _Every comment with the [OPTIONAL] prefix won't stop the approval of this PR. However, I strongly recommend you to take them into account as they can make your code better. Some of them were simply missed by the previous reviewer and addressing them will really improve your application._
 
Cheers and Happy coding! :clap:  :clap: :clap:

Feel free to leave any questions or comments in the PR thread if something is not 100% clear. Please, remember to tag me in your question so I can receive the notification.
 
 _As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561) you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._

**Pull request merged**
